#!/bin/sh
set -e
printf '%s\n' "$@" \
| xargs -t -I{python} env {python} setup.py build --build-lib build/{python}
cd tests
printf '%s\n' "$@" \
| xargs -t -I{python} env PYTHONPATH="$PWD/../build/{python}" {python} $(which nosetests) --verbose
