#!/bin/sh

# Copyright © 2015-2016 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of python-djvulibre.
#
# python-djvulibre is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# python-djvulibre is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

usage()
{
    printf 'Usage: %s [--no-build] [pythonX.Y...]\n' "$0"
}

args=$(getopt -n "$0" -o 'hj:' --long 'help,jobs:,no-build' -- "$@")
if [ $? -ne 0 ]
then
    usage >&2
    exit 1
fi
eval set -- "$args"
opt_jobs=$(nproc) || opt_jobs=1
opt_build=y
while true
do
    case "$1" in
        -h|--help) usage; exit 0;;
        -j|--jobs) opt_jobs=$2; shift 2;;
        --no-build) opt_build=; shift;;
        --) shift; break;;
        *) printf '%s: internal error (%s)\n' "$0" "$1" >&2; exit 1;;
    esac
done

set -e
[ $# = 0 ] && set -- python
[ -z $opt_build ] || \
printf '%s\n' "$@" \
| xargs -P"$opt_jobs" -t -I'{python}' env '{python}' setup.py build --build-lib 'build/{python}'
cd tests
nosetests=$(command -v nosetests) || { echo nosetests not found >&2; exit 1; }
printf '%s\n' "$@" \
| xargs -t -I'{python}' env PYTHONPATH="$PWD/../build/{python}" '{python}' "$nosetests" --verbose

# vim:ts=4 sts=4 sw=4 et
