#!/usr/bin/env bash

# Copyright © 2016-2019 Jakub Wilk <jwilk@jwilk.net>
#
# This file is part of python-djvulibre.
#
# python-djvulibre is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# python-djvulibre is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.

set -e -u
set -o pipefail
here=${0%/*}
here=${here#./}
root="$here/../"
root=${root#private/../}
rst2xml=$(command -v rst2xml) \
|| rst2xml=$(command -v rst2xml.py) \
|| { printf 'rst2xml not found\n' >&2; exit 1; }
rst2xml=${rst2xml##*/}
options='--input-encoding=UTF-8 --strict'
if [ $# -eq 0 ]
then
    print_desc='python setup.py --long-description'
    echo "(cd ${root:-.} && $print_desc) | $rst2xml $options - /dev/null" >&2
    (cd "${root:-.}" && $print_desc) | "$rst2xml" $options - /dev/null
fi
if [ $# -eq 0 ]
then
    grep -r -w -l ft=rst "${root}doc/"
else
    printf '%s\n' "$@"
fi |
xargs -L1 -t -I{} "$rst2xml" $options {} /dev/null

# vim:ts=4 sts=4 sw=4 et
