name: CI
on:
  push:
    branches-ignore:
    - appveyor
  pull_request:
jobs:
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
        - python: python-2.7
          djvulibre: djvulibre-3.5.21
          broken: broken
        - python: python-3.3
          djvulibre: djvulibre-3.5.27
          broken: broken
        - python: python-3.4
          djvulibre: djvulibre-3.5.27
          broken: broken
        - python: python-3.5
          djvulibre: djvulibre-3.5.28
        - python: python-3.6
          djvulibre: djvulibre-3.5.28
        - python: python-3.7
          djvulibre: djvulibre-3.5.28
        - python: python-3.8
          djvulibre: djvulibre-3.5.28
          broken: broken
        - python: python-3.9
          djvulibre: djvulibre-3.5.28
          broken: broken
        - python: python-3.10
          djvulibre: djvulibre-3.5.28
          broken: broken
    continue-on-error: ${{(matrix.broken && true) || false}}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: extract version numbers
      run: |
        echo "python-version=${python#python-}" >> $GITHUB_ENV
        echo "djvulibre-version=${djvulibre#djvulibre-}" >> $GITHUB_ENV
      env:
        djvulibre: ${{matrix.djvulibre}}
        python: ${{matrix.python}}
    - name: set up Python ${{env.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{env.python-version}}
        architecture: x86
    - name: add MSYS2 to PATH
      run: |
        echo 'C:\msys64\usr\bin\' >> $GITHUB_PATH
    - name: download DjVuLibre
      run: |
        mkdir -p download
        case ${{env.djvulibre-version}} in
          3.5.21) url='https://downloads.sourceforge.net/project/djvu/DjVuLibre_Windows/3.5.21%2B4.5/DjVuLibre%2BDjView-3.5.21%2B4.5-Setup.exe';;
          3.5.27) url='https://downloads.sourceforge.net/project/djvu/DjVuLibre_Windows/3.5.27%2B4.10/DjVuLibre-3.5.27_DjView-4.10.4_Setup.exe';;
          3.5.28) url='https://downloads.sourceforge.net/project/djvu/DjVuLibre_Windows/3.5.28%2B4.12/DjVuLibre-3.5.28_DjView-4.12_Setup.exe';;
          *) exit 1;
        esac
        wget "$url" -O download/djvulibre-setup.exe
    - name: install DjVuLibre
      shell: cmd
      run: |
        START /WAIT download\djvulibre-setup /S
      timeout-minutes: 1
    - name: add DjVuLibre to PATH
      run: |
        echo 'C:\Program Files (x86)\DjVuLibre\' >> $GITHUB_PATH
    - name: install Cython
      env:
        cython: ${{matrix.cython || 'cython'}}
      run: |
        pip install "${cython/-/==}"
    - name: install Visual C++ for Python 2.7
      if: matrix.python == 'python-2.7'
      run: |
        choco install vcpython27 -f -y
    - name: install setuptools
      run: |
        python -m pip install setuptools
    - name: build the extension in-place
      run: |
        PYTHONWARNINGS=error::FutureWarning python setup.py build_ext --inplace
    - name: run tests
      run: |
        python -m unittest discover tests/ -v

# vim:ts=2 sts=2 sw=2 et
